site: DL-HACK-20-21
url: 
title: DL-HACK-20-21
description: Deep Learning Hackathon - Track 1 hosted by Analytics Club, CFI, IIT-M

permalink: pretty

paginate:            1000
paginate_path:       "/page:num/"
baseurl:             ""
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: :compressed

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap  

collections:
  pages:
    output: true
    permalink: /:name
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      
  - scope:
      path: "assets/images"
    values:
      image: true

markdown: kramdown
